name: "🔐 Access Request"
description: "Request access to a specific feature, role, or environment."
title: "[Access] <short description>"
labels: [access]
body:
  - type: input
    id: feature
    attributes:
      label: "Feature/Area"
      description: "Which feature or area do you need access to?"
      placeholder: "e.g. Project Reports, Admin Dashboard"
    validations:
      required: true
  - type: input
    id: reason
    attributes:
      label: "Reason for Access"
      description: "Why do you need this access?"
      placeholder: "Describe your use case."
    validations:
      required: true
  - type: input
    id: duration
    attributes:
      label: "Access Duration"
      description: "How long do you need access? (if temporary)"
      placeholder: "e.g. 2 weeks, permanent"
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I have provided a valid reason for access."
          required: true
        - label: "I understand my responsibilities for data security."
          required: true
