name: "✨ Feature Request"
description: "Suggest a new feature or improvement for Kangalos."
title: "[Feature] <short description>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please describe your feature clearly and provide context for why it is needed.
  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Briefly describe the feature or improvement."
      placeholder: "A clear and concise summary."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation & Context"
      description: "Why is this feature needed? What problem does it solve?"
      placeholder: "Explain the use case and value."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed Solution"
      description: "Describe your proposed solution or implementation."
      placeholder: "How should this feature work?"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered alternative solutions?"
      placeholder: "List any alternatives."
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I have searched for existing feature requests."
          required: true
        - label: "This feature aligns with project goals and conventions."
          required: true
        - label: "All user-facing text will be translatable."
          required: true
