name: "♻️ Refactor Request"
description: "Suggest a code refactor or technical debt cleanup."
title: "[Refactor] <short description>"
labels: [refactor, tech debt]
body:
  - type: input
    id: area
    attributes:
      label: "Area/Component"
      description: "Which part of the codebase needs refactoring?"
      placeholder: "e.g. src/features/auth, src/components/global"
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: "Refactor Reason"
      description: "Why does this need refactoring?"
      placeholder: "Describe the technical debt or code smell."
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: "Suggested Refactor"
      description: "How should this be improved?"
      placeholder: "Describe your refactor idea."
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked for existing refactor requests."
          required: true
        - label: "This refactor aligns with project conventions."
          required: true
