name: "🚨 Security Issue"
description: "Report a security vulnerability or concern."
title: "[Security] <short description>"
labels: [security]
body:
  - type: input
    id: area
    attributes:
      label: "Area/Component"
      description: "Which part of the system is affected?"
      placeholder: "e.g. Auth, API, File Uploads"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Vulnerability Description"
      description: "Describe the security issue in detail."
      placeholder: "What is the vulnerability?"
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: "Potential Impact"
      description: "What could an attacker achieve?"
      placeholder: "Describe the risk."
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: "Suggested Mitigation"
      description: "How could this be fixed or mitigated?"
      placeholder: "Suggest a fix or workaround."
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I have not publicly disclosed this issue."
          required: true
        - label: "I have provided all necessary details for triage."
          required: true
