name: "🌐 Translation Request"
description: "Request a new translation key or report a translation issue."
title: "[Translation] <short description>"
labels: [i18n, translation]
body:
  - type: input
    id: key
    attributes:
      label: "Translation Key"
      description: "What is the key or string to add/fix?"
      placeholder: "e.g. project.status.completed"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Where is this string used? Provide file/component name."
      placeholder: "e.g. src/features/projects/ProjectCard.tsx"
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: "Suggested Translation(s)"
      description: "Provide translations for en, fr, ko if possible."
      placeholder: "en: Completed\nfr: Terminé\nko: 완료됨"
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked all /src/messages/*.json files."
          required: true
        - label: "I have used the translation system, not hardcoded text."
          required: true
